# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-7.1

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/snapframework/heist.git
    commit: 929ebf1ba7868c5fddae584e778548f19029c3ab
- location:
    git: https://github.com/snapframework/io-streams-haproxy.git
    commit: 0a64cba062a0049d9dcdc438aa9758a843c8dfae
- location:
    git: https://github.com/snapframework/snap-server.git
    commit: b7ef5a1348c3f01456d77c2ef7177ecb216c9476
- location:
    git: https://github.com/snapframework/snap-core.git
    commit: e1e6ffcbd7ced448123bc5ed3d4da9f95c75206c
- location:
    git: https://github.com/snapframework/snap.git
    commit: ec141e953493d4d29b57ad422fa6d4218320b3a2
- location:
    git: https://github.com/dbp/hspec-snap.git
    commit: 5c55326a6e4cbefa5374700a33aad594bd25c8b2
- location:
    git: https://github.com/sigrlami/digestive-functors
    commit: 66604c9d22ba622ebb3d7ce37afb4908eaff2c86
  subdirs:
  - digestive-functors
- location:
    git: https://github.com/haskell-servant/servant.git
    commit: 6999b002977fa1a726ea627f716e47c677047713
  subdirs:
  - servant
- location:
    git: https://github.com/dbp/hspec-snap.git
    commit: 5c55326a6e4cbefa5374700a33aad594bd25c8b2
- location:
    git: https://github.com/snapframework/snap-loader-dynamic.git
    commit: 98047f0f1b95ed3b54d8bf117258bd001f6f5f8b
- location:
    git: https://github.com/snapframework/snap-loader-static.git
    commit: a31b7a418894d944cf9ff52262e213f9d5cea437  
           
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)

extra-deps:
   - aeson-0.11.1.4
   - base-orphans-0.5.4
   - text-1.2.2.1
   - map-syntax-0.2.0.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
